## 리스트로 배열 생성

- 1차원, 2차원, 3차원

In [ ]:
import numpy as np

########## 리스트로부터 배열 생성
# 1차원 배열 생성 (1~5)
arr1d = np.array([1,2,3,4,5])
print(f"1차원 배열 : {arr1d}")
print(f" -shape : {arr1d.shape}")
print(f" -ndim : {arr1d.ndim}")
print(f" -dtype : {arr1d.dtype}")

# 2차원 배열 생성 (3x3)
arr2d = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]]) # np.array()는 인자를 하나만 받는 함수
print(f"2차원 배열 : \n{arr2d}")
print(f" -shape : {arr2d.shape}")
print(f" -ndim : {arr2d.ndim}")

# 3차원 배열 생성 (2x2x3)
arr3d = np.array([[[1,2,3],[4,5,6]],
                  [[7,8,9],[10,11,12]]])
print(f"3차원 배열 : \n{arr3d}")
print(f"3차원 배열 shape : {arr3d.shape}")

1차원 배열 : [1 2 3 4 5]
 -shape : (5,)
 -ndim : 1
 -dtype : int64


## 특수 배열 생성

- zeros, ones, full, eye, diag

In [ ]:
# 특수 배열 생성
# zeros : 0으로 채워진 배열 생성 (3x4)
zeros_arr = np.zeros((3,4))
print(f"zeros (3x4) :\n{zeros_arr}")

# ones : 1로 채워진 배열 생성 (2x3)
ones_arr = np.ones((2,3))
print(f"ones (2x3) : \n{ones_arr}")

# full : 특정 값으로 채워진 배열 생성 (2x3, 값=7)
full_arr = np.full((2,3), 7)
print(f"full (2x3, value=7)\n{full_arr}")

# eye : 단위 행렬 생성 (4x4)
eye_arr = np.eye(4)
print(f"eye (4x4) : \n{eye_arr}")

# diag : 대각 행렬 생성
diag_arr = np.diag([1,2,3,4])
print(f"diag([1,2,3,4]) : \n{diag_arr}")

zeros (3x4) :
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## 배열 생성, 분할
- arange, linspace, logspace

In [34]:
# 0 부터 9까지 정수 배열
arr_arange1 = np.arange(10)
print(f"arange(10) : {arr_arange1}")

# 5부터 15까지 2씩 증가
arr_arange2 = np.arange(5,16,2)
print(f"arange(5,15,2) : {arr_arange2}")

# 0부터 1까지 5개로 균등 분할
arr_linspace = np.linspace(0,1,5)
print(f"linespace(0,1,5) : {arr_linspace}")

# 0부터 100까지 11개로 균등 분할
arr_linspace2 = np.linspace(0,100,11)
print(f"linspace(0,100,11) : {arr_linspace2}")

# 10^0 부터 10^3까지 4개
arr_logspace = np.logspace(0,3,4)
print(f"logspace(0,3,4) : {arr_logspace}")

arange(10) : [0 1 2 3 4 5 6 7 8 9]
arange(5,15,2) : [ 5  7  9 11 13 15]
linespace(0,1,5) : [0.   0.25 0.5  0.75 1.  ]
linspace(0,100,11) : [  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
logspace(0,3,4) : [   1.   10.  100. 1000.]


## 난수 배열 생성
- rand, randn, randint, choice

In [40]:
# 재현성을 위한 시드 설정
np.random.seed(42)

# rand : 0~1 균등 분포 난수 (3x3)
rand_uniform = np.random.rand(3, 3)
print(f"정규 분포 난수 (3x3) : \n{rand_uniform}")

# randn : 표준 정규 분포 난수 (3x3)
rand_normal = np.random.randn(3,3)
print(f"정규 분포 난수 (3x3) : \n{rand_normal}")

# randint : 정수 난수
rand_int = np.random.randint(0, 10, size=(3,3))
print(f"정수 난수 0~10 (3x3) : \n{rand_int}")

# choice : 리스트에서 무작위 선택
choices = np.random.choice(['A', 'B', 'C', 'D'], size=5)
print(f"무작위 선택 : {choices}")

정규 분포 난수 (3x3) : 
[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]
정규 분포 난수 (3x3) : 
[[-0.58087813 -0.52516981 -0.57138017]
 [-0.92408284 -2.61254901  0.95036968]
 [ 0.81644508 -1.523876   -0.42804606]]
정수 난수 0~10 (3x3) : 
[[2 6 3]
 [8 2 4]
 [2 6 4]]
무작위 선택 : ['A' 'C' 'B' 'D' 'A']


## dtype 지정과 반환
- dtype 배열 생성, astype으로 형변환

In [ ]:
# float32로 배열 생성
arr_float32 = np.array([1,2,3], dtype=np.float32)
print(f"float32 배열 : {arr_float32}, dtype: {arr_float32.dtype}")

# complex128로 배열 생성
arr_complex = np.array([1,2,3], dtype=np.complex128)
print(f"complex128 배열 : {arr_complex}, dtype : {arr_complex.dtype}")

# astype으로 형 변환
arr_float = np.array([1.7, 2.3, 3.9])
arr_converted = arr_float.astype(np.int32)
print(f"원본 (float) : {arr_float}")
print(f"변환 (int32 : {arr_converted})")

float32 배열 : [1. 2. 3.], dtype: float32
complex128 배열 : [1.+0.j 2.+0.j 3.+0.j], drype : complex128
원본 (float) : [1.7 2.3 3.9]
변환 (int32 : [1 2 3])


## reshape

In [52]:
# 1차원 배열 생성
arr = np.arange(12)
print(f"원본 배열 : {arr}")

# (3,4)로 reshape
arr_3x4 = arr.reshape(3, 4)
print(f"reshape(3,4) : \n{arr_3x4}")

# (2, 6)으로 reshape
arr_2x6 = arr.reshape(2, 6)
print(f"reshape(2, 6) : \n{arr_2x6}")

# (2, 2, 3)으로 reshape
arr_2x2x3 = arr.reshape(2,2,3)
print(f"reshape(2, 2, 3) : \n{arr_2x2x3}")

# -1 사용 (자동 계산)
arr_auto = arr.reshape(4, -1)
print(f"reshape(4, -1) => shape : {arr_auto.shape}")


원본 배열 : [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshape(3,4) : 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
reshape(2, 6) : 
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
reshape(2, 2, 3) : 
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
reshape(4, -1) => shape : (4, 3)


In [77]:
# 도전 과제
# 1. 1 부터 100 까지의 숫자 중 3의 배수만 포함하는 배열 생성
arr_3x = np.arange(3, 100, 3)
print(f" 1부터 100까지 3의 배수 : \n {arr_3x}")

# 2. 5x5 체커보드 패턴 생성 (0과 1이 번갈아 나타남)
zeros_5x5 = np.zeros((5,5))
zeros_5x5[0:5:2, 1:4:2] = 1
zeros_5x5[1:3:2, 0:4:2] = 1
print(f"채커보드 :\n {zeros_5x5}")

# 3. 평균이 50, 표준편차가 10인 정규분포에서 1000개 샘플 추출 후
#    기본 통계량 (평균, 표준편차, 초소, 최대) 출력
arr = np.random.normal(loc = 50, scale = 10, size = 1000)
arr_mean = round(arr.mean(), 2)
arr_std = round(arr.std(), 2)
arr_min = round(arr.min(), 2)
arr_max = round(arr.max(), 2)
print(f"평균 : {arr_mean}, 표준편차 : {arr_std}, \
최소 : {arr_min}, 최대 : {arr_max}")

 1부터 100까지 3의 배수 : 
 [ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]
채커보드 :
 [[0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 0.]
 [0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0.]]
평균 : 50.07, 표준편차 : 9.85, 최소 : 20.09, 최대 : 89.26
