In [1]:
import numpy as np

## 기본 인덱싱

In [6]:
# 1차원 배열 생성
arr1d = np.array([10,20,30,40,50,60,70,80,90,100])
print(f"1차원 배열 : {arr1d}")

# 첫 번째 요소
print(f"첫 번째 요소 arr1d[0]: {arr1d[0]}")

# 마지막 요소
print(f"마지막 요소 arr1d[-1]: {arr1d[-1]}")

# 세 번째 요소
print(f"세 번째 요소 arr1d[2]: {arr1d[2]}")

# 뒤에서 세 번째 요소
print(f"뒤에서 세 번째 요소 arr1d[-3] : {arr1d[-3]}")

1차원 배열 : [ 10  20  30  40  50  60  70  80  90 100]
첫 번째 요소 arr1d[0]: 10
마지막 요소 arr1d[-1]: 100
세 번째 요소 arr1d[2]: 30
뒤에서 세 번째 요소 arr1d[-3] : 80


## 다차원 배열 인덱싱

In [ ]:
# 2차원 배열 생성
arr2d = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16]])
print(f"2차원 배열 : \n{arr2d}")

# (0, 0) 위치 요소
print(f"arr2d[0, 0] : {arr2d[0, 0]}")

# (2, 3) 위치 요소
print(f"arr2d[2, 3] : {arr2d[2, 3]}")

# 마지막 행, 마지막 열 요소
print(f"arr2d[-1, -1] : {arr2d[-1, -1]}")

# 두 번째 행 전체
print(f"arr2d[1] : {arr2d[1]}")

# 세 번째 열 전체
print(f"arr2d[: , 2] : {arr2d[:, 2]}")

2차원 배열 : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
arr2d[0, 0] : 1
arr2d[2, 3] : 12
arr2d[-1, -1] : 16
arr2d[1] : [5 6 7 8]
arr2d[: , 2] : [ 3  7 11 15]


## 기본 슬라이싱

In [19]:
arr = np.arange(10)
print(f"원본 배열 : {arr}")

# 인덱스 2~6
print(f"arr[2:7] : {arr[2:7]}")

# 처음부터 5번째 까지
print(f"arr[:5] : {arr[:5]}")

# 2씩 건너뛰기 
print(f"arr[::2] : {arr[::2]}")

# 역순
print(f"arr[::-1] : {arr[::-1]}")

# 역순으로 2씩 건너뛰기
print(f"arr[::-2] : {arr[::-2]}")

원본 배열 : [0 1 2 3 4 5 6 7 8 9]
arr[2:7] : [2 3 4 5 6]
arr[:5] : [0 1 2 3 4]
arr[::2] : [0 2 4 6 8]
arr[::-1] : [9 8 7 6 5 4 3 2 1 0]
arr[::-2] : [9 7 5 3 1]


## 다차원 슬라이싱

In [30]:
arr2d = np.arange(1,17).reshape(4, 4)
print(f"4x4 배열 : \n {arr2d}")

# 상위 2x2 부분 행렬
top_left = arr2d[:2, :2]
print(f"상위 2x2 arr2d[:2, :2] :\n {top_left}")

# 하위 2x2 부분 행혈
bottom_right = arr2d[2:, 2:]
print(f"하위 2x2 arr2d[2:, 2:] : \n {bottom_right}")

# 가운데 2x2 부분 행렬
center = arr2d[1:3, 1:3]
print(f"가운데 2x2 arr2d[1:3, 1:3] :\n {center}")

# 모든 행의 첫 번째와 마지막 열
first_last_cols = arr2d[:, (0,-1)]
print(f"첫 번째, 마지막 열 arr2d[:, (0,-1)]:\n {first_last_cols}")

# 짝수 행만 
even_rows = arr2d[1::2]
print(f"짝수 행 arr2d[1::2] :\n {even_rows}")

4x4 배열 : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
상위 2x2 arr2d[:2, :2] :
 [[1 2]
 [5 6]]
하위 2x2 arr2d[2:, 2:] : 
 [[11 12]
 [15 16]]
가운데 2x2 arr2d[1:3, 1:3] :
 [[ 6  7]
 [10 11]]
첫 번째, 마지막 열 arr2d[:, (0,-1)]:
 [[ 1  4]
 [ 5  8]
 [ 9 12]
 [13 16]]
짝수 행 arr2d[1::2] :
 [[ 5  6  7  8]
 [13 14 15 16]]


## 팬시 인덱싱 (Fancy Indexing)

In [36]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(f"원본 배열: {arr}")

# 인덱스 [0,2,5,9]의 요소들
indices = [0,2,5,9]
selected = arr[indices]
print(f"arr[[0,2,5,9]] : {selected}")

# 2D 배열에서 팬시 인덱싱
arr2d = np.arange(1, 17).reshape(4, 4)
print(f"4x4 배열 : \n{arr2d}")

# 0, 2번째 행 선택
rows = arr2d[[0, 2]]
print(f"arr2d[[0,2]] (0, 2번째 행) : \n {rows}")

# 대각선 요소 선택
diagonal = arr2d[[0,1,2,3], [0,1,2,3]]
print(f"대각선 요소 : {diagonal}")

# 역대각선 요소 선택
anti_diagonal = arr2d[[0,1,2,3], [3,2,1,0]]
print(f"역대각선 요소 : {anti_diagonal}")

원본 배열: [ 10  20  30  40  50  60  70  80  90 100]
arr[[0,2,5,9]] : [ 10  30  60 100]
4x4 배열 : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
arr2d[[0,2]] (0, 2번째 행) : 
 [[ 1  2  3  4]
 [ 9 10 11 12]]
대각선 요소 : [ 1  6 11 16]
역대각선 요소 : [ 4  7 10 13]


## 불리언 인덱싱 (Boolean Indexing)

In [43]:
arr = np.array([15, 8, 23, 4, 42, 16, 7, 35, 19, 50])
print(f"원본 배열: {arr}")

# 20보다 큰 요소
mask_gt20 = arr > 20
print(f"조건 (arr > 20) : {mask_gt20}")
print(f"20보다 큰 요소 : {arr[mask_gt20]}")

# 짝수 요소
even_elements = arr[arr % 2 == 0]
print(f"짝수 요소 : {even_elements}")

# 10~30 사이의 요소
range_elements = arr[(arr >= 10) & (arr <= 30)]
print(f"10~30 사이 : {range_elements}")

# 10미만 40 초과
extreme_elements = arr[(arr > 40) | (arr < 10)]
print(f"10 미만 또는 40 초과 : {extreme_elements}")

# 2D 배열에서 불리언 인덱싱
arr2d = np.arange(1, 17).reshape(4, 4)
print(f"\n4x4 배열:\n{arr2d}")

# 8보다 큰 요소 (1D로 반환됨)
gt8 = arr2d[arr2d > 8]
print(f"8보다 큰 요소 : {gt8}")

원본 배열: [15  8 23  4 42 16  7 35 19 50]
조건 (arr > 20) : [False False  True False  True False False  True False  True]
20보다 큰 요소 : [23 42 35 50]
짝수 요소 : [ 8  4 42 16 50]
10~30 사이 : [15 23 16 19]
10 미만 또는 40 초과 : [ 8  4 42  7 50]

4x4 배열:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
8보다 큰 요소 : [ 9 10 11 12 13 14 15 16]


## 조건에 따른 값 변경

In [48]:
arr = np.array([1, 5, 3, 8, 2, 9, 4, 7, 6, 10])
print(f"원본 배열: {arr}")

# 5보다 큰 값을 0으로 변경
arr_copy = arr.copy()
arr_copy[arr_copy > 5] = 0
print(f"5보다 큰 값 => 0 : {arr_copy}")

# np.where을 사용한 조건부 변경
result = np.where(arr>5, arr*2, arr)
print(f"5보다 크면 2배, 아니면 유지 : {result}")

# np.clip을 사용한 범위 제한
cliped = np.clip(arr, 3, 7)
print(f" np.clip(arr,3,7) : {cliped}")

원본 배열: [ 1  5  3  8  2  9  4  7  6 10]
5보다 큰 값 => 0 : [1 5 3 0 2 0 4 0 0 0]
5보다 크면 2배, 아니면 유지 : [ 1  5  3 16  2 18  4 14 12 20]
 np.clip(arr,3,7) : [3 5 3 7 3 7 4 7 6 7]


## 뷰(view)와 복사(copy)

In [53]:
# view 예시
arr = np.array([1,2,3,4,5])
view = arr[1:4] # 슬라이싱은 뷰
print(f"원본 배열 : {arr}")
print(f"슬라이스 (view) : {view}")

view[0] = 100 # view 수정
print(f"view 수정 후 원본 : {arr}")

# copy 예시
arr = np.array([1, 2, 3, 4, 5])
copy = arr[1:4].copy()  # 명시적 복사
print(f"\n원본 배열: {arr}")
print(f"복사본: {copy}")

copy[0] = 100 # 복사본 수정
print(f"복사복 수정 후 원본 : {arr}") # 원본 유지

# 뷰인지 확인하는 방법
arr = np.array([1,2,3,4,5])
view = arr[1:4]
copy = arr[1:4].copy()

print(f"\nview.base is arr: {view.base is arr}")  # True (뷰)
print(f"copy.base is arr: {copy.base is arr}")    # False (복사)

원본 배열 : [1 2 3 4 5]
슬라이스 (view) : [2 3 4]
view 수정 후 원본 : [  1 100   3   4   5]

원본 배열: [1 2 3 4 5]
복사본: [2 3 4]
복사복 수정 후 원본 : [1 2 3 4 5]

view.base is arr: True
copy.base is arr: False


In [ ]:
# 1. 5x5 배열에서 테두리 요소만 추출하기
arr = np.arange(1, 26).reshape(5, 5)
print(f"5x5 배열:\n{arr}")

top = arr[0 , :]
middle = arr[1:4, (0,4)]
bottom = arr[-1, :]
print(top)
print(middle)
print(bottom)

top = arr[0, :]
bottom = arr[-1, :]
left = arr[1:-1, 0]
right = arr[1:-1, -1]
border = np.concatenate([top, right, bottom[::-1], left[::-1]])
print(f"테두리 요소 (시계방향): {border}")


5x5 배열:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[1 2 3 4 5]
[[ 6 10]
 [11 15]
 [16 20]]
[21 22 23 24 25]
테두리 요소 (시계방향): [ 1  2  3  4  5 10 15 20 25 24 23 22 21 16 11  6]


In [65]:
#학생 성적 배열에서 60점 이상인 학생만 필터링하고,
#80점 이상은 'A', 70점 이상은 'B', 나머지는 'C' 등급 부여
scores = np.array([85, 72, 45, 90, 65, 78, 55, 88, 95, 62])
print(f"성적: {scores}")

gt60 = scores[scores >= 60]
result = np.where(gt60 >= 80, 'A', np.where(gt60 >=70 , 'B','C' ))
print(result)

성적: [85 72 45 90 65 78 55 88 95 62]
['A' 'B' 'A' 'C' 'B' 'A' 'A' 'C']


In [67]:
# 3. 6x6 배열에서 3x3블록 4개로 분할하기
arr = np.arange(36).reshape(6, 6)

block1 = arr[:3, :3]
block2 = arr[:3, 3:]
block3 = arr[3:, :3]
block4 = arr[3:, 3:]

print(f"\n블록 1 (좌상단):\n{block1}")
print(f"\n블록 2 (우상단):\n{block2}")
print(f"\n블록 3 (좌하단):\n{block3}")
print(f"\n블록 4 (우하단):\n{block4}")


블록 1 (좌상단):
[[ 0  1  2]
 [ 6  7  8]
 [12 13 14]]

블록 2 (우상단):
[[ 3  4  5]
 [ 9 10 11]
 [15 16 17]]

블록 3 (좌하단):
[[18 19 20]
 [24 25 26]
 [30 31 32]]

블록 4 (우하단):
[[21 22 23]
 [27 28 29]
 [33 34 35]]
