In [1]:
import numpy as np

## 스칼라와 배열 연산

In [6]:
arr = np.array([1, 2, 3, 4, 5])
print(f"원본 배열: {arr}")

# 스칼라 덧셈
print(f"arr + 10 : {arr + 10}")

# 스칼라 곱셈
print(f"arr * 3 : {arr * 3}")

# 스칼라 나눗셈
print(f" arr / 2 : {arr/2}")

# 스칼라 거듭제곱
print(f"arr ** 2 : {arr ** 2}")

# 2D 배열과 스칼라
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6]])
print(f"\n2D 배열:\n{arr2d}")
print(f"arr2d * 2:\n{arr2d * 2}")

원본 배열: [1 2 3 4 5]
arr + 10 : [11 12 13 14 15]
arr * 3 : [ 3  6  9 12 15]
 arr / 2 : [0.5 1.  1.5 2.  2.5]
arr ** 2 : [ 1  4  9 16 25]

2D 배열:
[[1 2 3]
 [4 5 6]]
arr2d * 2:
[[ 2  4  6]
 [ 8 10 12]]


## 1D 배열과 2D 배열 연산

In [10]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
arr1d = np.array([10, 20, 30])

print(f"2D 배열 (3x3): \n {arr2d}")
print(f"1D 배열: {arr1d}")

# 2D + 1D (행에 더하기)
result_add = arr2d + arr1d
print(f"arr2d + arr1d (각 행에 더함) : \n{result_add}")

# 2D * 1D (행에 곱하기)
result_mul = arr2d * arr1d
print(f"arr2d * arr1d (각 행에 곱함) : \n{result_mul}")

# 브로드캐스팅 과정 설명
print(f"[브로드캐스팅 과정]")
print(f"arr2d shape: {arr2d.shape}")
print(f"arr1d shape : {arr1d.shape}")
print("-> arr1d는 (1, 3)으로 확장")
print("-> (1, 3)이 (3, 3)으로 브로드캐스트")

2D 배열 (3x3): 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
1D 배열: [10 20 30]
arr2d + arr1d (각 행에 더함) : 
[[11 22 33]
 [14 25 36]
 [17 28 39]]
arr2d * arr1d (각 행에 곱함) : 
[[ 10  40  90]
 [ 40 100 180]
 [ 70 160 270]]
[브로드캐스팅 과정]
arr2d shape: (3, 3)
arr1d shape : (3,)
-> arr1d는 (1, 3)으로 확장
-> (1, 3)이 (3, 3)으로 브로드캐스트


## 열 방향 브로드캐스팅

In [13]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
col_vector = np.array([[10], [20], [30]]) # (3,1) shape

print(f"2D 배열 (3x3) :\n {arr2d}")
print(f"열 벡터 (3x1): \n{col_vector}")

result = arr2d + col_vector
print(f"\narr2d + col_vector (각 열에 더함):\n{result}")

# reshape을 이용한 열 벡터 생성
arr1d = np.array([10, 20, 30])
col_reshaped = arr1d.reshape(-1, 1)  # (3, 1)로 변환
print(f"\nreshape(-1, 1)로 열 벡터 생성: shape = {col_reshaped.shape}")

2D 배열 (3x3) :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
열 벡터 (3x1): 
[[10]
 [20]
 [30]]

arr2d + col_vector (각 열에 더함):
[[11 12 13]
 [24 25 26]
 [37 38 39]]

reshape(-1, 1)로 열 벡터 생성: shape = (3, 1)


## 외적 연산 (Outer Product)

In [16]:
row = np.array([1, 2, 3])      # (3,)
col = np.array([[10], [20], [30]])  # (3, 1)

print(f"행 벡터: {row}")
print(f"열 벡터:\n{col}")

# TODO: 외적 (곱셈표)
outer_product = col * row  # (3,1) * (3,) = (3,3)
print(f"\n외적 (col * row):\n{outer_product}")

# np.outer 함수 사용
outer_np = np.outer([10, 20, 30], [1, 2, 3])
print(f"\nnp.outer 결과:\n{outer_np}")

행 벡터: [1 2 3]
열 벡터:
[[10]
 [20]
 [30]]

외적 (col * row):
[[10 20 30]
 [20 40 60]
 [30 60 90]]

np.outer 결과:
[[10 20 30]
 [20 40 60]
 [30 60 90]]


## 브로드캐스팅 규칙 확인

In [17]:
# 호환 가능한 shape 조합
print("호환 가능한 조합:")
combinations = [
    ((3, 4), (4,)),
    ((3, 4), (1, 4)),
    ((3, 4), (3, 1)),
    ((5, 3, 4), (3, 4)),
    ((5, 3, 4), (1, 4)),
    ((5, 1, 4), (3, 1)),
]

for shape1, shape2 in combinations:
    result_shape = np.broadcast_shapes(shape1, shape2)
    print(f"  {shape1} + {shape2} → {result_shape}")

# 호환 불가능한 조합
print("\n호환 불가능한 조합:")
incompatible = [
    ((3, 4), (5,)),
    ((3, 4), (2, 3)),
    ((5, 3, 4), (2, 4)),
]

for shape1, shape2 in incompatible:
    try:
        np.broadcast_shapes(shape1, shape2)
    except ValueError as e:
        print(f"  {shape1} + {shape2} → Error!")


호환 가능한 조합:
  (3, 4) + (4,) → (3, 4)
  (3, 4) + (1, 4) → (3, 4)
  (3, 4) + (3, 1) → (3, 4)
  (5, 3, 4) + (3, 4) → (5, 3, 4)
  (5, 3, 4) + (1, 4) → (5, 3, 4)
  (5, 1, 4) + (3, 1) → (5, 3, 4)

호환 불가능한 조합:
  (3, 4) + (5,) → Error!
  (3, 4) + (2, 3) → Error!
  (5, 3, 4) + (2, 4) → Error!


## 실용적인 브로드캐스팅 예제

In [24]:
# 1: 데이터 정규화 (Z-score)
print("\n[예제 1] 데이터 표준화")
data = np.array([[65, 70, 75],
                 [80, 85, 90],
                 [70, 75, 80]])
print(f"원본 데이터:\n{data}")

mean = data.mean(axis=0)  # 열별 평균
std = data.std(axis=0)    # 열별 표준편차
print(f"열별 평균: {mean}")
print(f"열별 표준편차: {std}")

normalized = (data - mean) / std  # 브로드캐스팅
print(f"표준화 결과:\n{normalized}")


[예제 1] 데이터 표준화
원본 데이터:
[[65 70 75]
 [80 85 90]
 [70 75 80]]
열별 평균: [71.66666667 76.66666667 81.66666667]
열별 표준편차: [6.23609564 6.23609564 6.23609564]
표준화 결과:
[[-1.06904497 -1.06904497 -1.06904497]
 [ 1.33630621  1.33630621  1.33630621]
 [-0.26726124 -0.26726124 -0.26726124]]


In [26]:
# 2: 거리 계산 (유클리드 거리)
print("\n[예제 2] 거리 계산")
points = np.array([[0, 0],
                   [1, 0],
                   [0, 1],
                   [1, 1]])
center = np.array([0.5, 0.5])
print(f"점들:\n{points}")
print(f"중심점: {center}")

distances = np.sqrt(np.sum((points - center) ** 2, axis=1))
print(f"중심점으로부터 거리: {distances}")


[예제 2] 거리 계산
점들:
[[0 0]
 [1 0]
 [0 1]
 [1 1]]
중심점: [0.5 0.5]
중심점으로부터 거리: [0.70710678 0.70710678 0.70710678 0.70710678]


In [44]:
# 3: 이미지 밝기 조절
print("\n[예제 3] 이미지 밝기 조절 (시뮬레이션)")
image = np.random.randint(0, 256, (3, 3), dtype=np.uint8)
print(f"원본 이미지:\n{image}")

# 밝기 증가 (브로드캐스팅)
brightness_increase = 50
brighter = np.clip(image + brightness_increase)
print(f"밝기 +50:\n{brighter}")


[예제 3] 이미지 밝기 조절 (시뮬레이션)
원본 이미지:
[[159 233 126]
 [ 62 204 134]
 [122  73  68]]
밝기 +50:
[[209  27 176]
 [112 254 184]
 [172 123 118]]
