In [15]:
import numpy as np

print("="*60)
print("NumPy ndarray 생성 실습")
print("="*60)

# =========================================
print("\n[실습 1-1] 리스트로부터 배열 생성")
print("-"*40)

# TODO : 1차원 배열 생성 (1~5)
arr1d = np.array([1, 2, 3, 4, 5])
print(f"1차원 배열 ; {arr1d}")
print(f" - shape : {arr1d.shape}")
print(f" - ndim : {arr1d.ndim}")
print(f" - dtype : {arr1d.dtype}")

NumPy ndarray 생성 실습

[실습 1-1] 리스트로부터 배열 생성
----------------------------------------
1차원 배열 ; [1 2 3 4 5]
 - shape : (5,)
 - ndim : 1
 - dtype : int64


In [11]:
import numpy as np

arr1d = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr1d = arr1d.reshape(2, 2, 2)
arr1d.ndim

3

In [14]:
arr2d = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
print(f"\n2차원 배열 : \n {arr2d}")
print(f" - shqpe : {arr2d.shape}")
print(f" - ndim : {arr2d.ndim}")

arr3d = np.array([[[1, 2, 3,], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])
print(f"\n3차원 배열 shape : {arr3d.shape}")


2차원 배열 : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
 - shqpe : (3, 3)
 - ndim : 2

3차원 배열 shape : (2, 2, 3)


In [ ]:
zeros_arr = np.zeros((3, 4))
print(f"zeros (3x4): \n{zeros_arr}") # dtype : float64

zeros (3x4): 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
ones_arr = np.ones((2, 3))
print(f"\nones (2x3) : \n {ones_arr}") # dtype : float64


ones (2x3) : 
 [[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
full_arr = np.full((2, 2), 7)
print(f"\nfull (2x2, value=7): \n{full_arr}") # dtype : int


full (2x2, value=7): 
[[7 7]
 [7 7]]


In [20]:
eye_arr = np.eye(4)
print(f"\neye (4x4): \n{eye_arr}")


eye (4x4): 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# 대각 행렬
diag_arr = np.diag([1, 2, 3, 4])
print(f"\ndiag([1, 2, 3, 4]):\n{diag_arr}")


diag([1, 2, 3, 4]):
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [24]:
arr_arange1 = np.arange(10)
print(f"arange(10) : {arr_arange1}")

arange(10) : [0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr_arange2 = np.arange(5, 15, 2) 
print(f"arange(5, 15, 2) : {arr_arange2}") # numpy는 배열을 출력할 때 가장 큰 숫자의 자릿수에 맞춰서 정렬 실제 데이터에 공백이 있는건 아님

arange(5, 15, 2) : [ 5  7  9 11 13]


In [26]:
arr_linspace = np.linspace(0, 1, 5)
print(f"linspace(0, 1, 5): {arr_linspace}")

linspace(0, 1, 5): [0.   0.25 0.5  0.75 1.  ]


In [27]:
arr_linspace2 = np.linspace(0, 100, 11)
print(f"linspace(0, 100, 11): {arr_linspace2}")

linspace(0, 100, 11): [  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [30]:
arr_logspace = np.logspace(0, 3, 4)
print(f"logspace(0, 3, 4): {arr_logspace}")

logspace(0, 3, 4): [   1.   10.  100. 1000.]


In [45]:

# 재현성을 위한 시드 설정
np.random.seed(42)

# TODO: rand - 0~1 균등 분포 난수 (3x3)
rand_uniform = np.random.rand(3, 3)
print(f"균등 분포 난수 (3x3):\n{rand_uniform}")

# TODO: randn - 표준 정규 분포 난수 (3x3)
rand_normal = np.random.randn(3, 3)
print(f"\n정규 분포 난수 (3x3):\n{rand_normal}")

# TODO: randint - 0~10 정수 난수 (3x3)
rand_int = np.random.randint(0, 10, size=(3, 3))
print(f"\n정수 난수 0~10 (3x3):\n{rand_int}")

# TODO: choice - 리스트에서 무작위 선택
choices = np.random.choice(['A', 'B', 'C', 'D'], size=5)
print(f"\n무작위 선택: {choices}")

균등 분포 난수 (3x3):
[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]

정규 분포 난수 (3x3):
[[-0.58087813 -0.52516981 -0.57138017]
 [-0.92408284 -2.61254901  0.95036968]
 [ 0.81644508 -1.523876   -0.42804606]]

정수 난수 0~10 (3x3):
[[2 6 3]
 [8 2 4]
 [2 6 4]]

무작위 선택: ['A' 'C' 'B' 'D' 'A']


In [ ]:
print("\n[실습 1-5] dtype 지정과 변환")
print("-" * 40)

# TODO: float32로 배열 생성
arr_float32 = np.array([1, 2, 3], dtype=np.float32)
print(f"float32 배열: {arr_float32}, dtype: {arr_float32.dtype}")

# TODO: complex128로 배열 생성
arr_complex = np.array([1, 2, 3], dtype=np.complex128)
print(f"complex128 배열: {arr_complex}, dtype: {arr_complex.dtype}")

# TODO: astype으로 형변환
arr_int = np.array([1.7, 2.3, 3.9])
arr_converted = arr_int.astype(np.int32) # float => int
print(f"\n원본 (float): {arr_int}")
print(f"변환 (int32): {arr_converted}")


In [ ]:
temp = np.arange(4)
temp = temp.reshape(4, 1)
print(temp)

[[0]
 [1]
 [2]
 [3]]


In [ ]:
temp = np.arange(4)
temp = temp.reshape(2, -1) # 자동 배열 완성 => 2개의 행으로 이뤄진 배열
print(temp)

[[0 1]
 [2 3]]


In [55]:
arr = np.arange(12)
print(f"원본 배열: {arr}")

# TODO: (3, 4)로 reshape
arr_3x4 = arr.reshape(3, 4)
print(f"\nreshape(3, 4):\n{arr_3x4}")

# TODO: (2, 6)로 reshape
arr_2x6 = arr.reshape(2, 6)
print(f"\nreshape(2, 6):\n{arr_2x6}")

# TODO: (2, 2, 3)로 reshape
arr_2x2x3 = arr.reshape(3, 2, 2)
print(f"\nreshape(2, 2, 3):\n{arr_2x2x3}")

# TODO: -1 사용 (자동 계산)
arr_auto = arr.reshape(4, -1)
print(f"\nreshape(4, -1) -> shape: {arr_auto.shape}")

원본 배열: [ 0  1  2  3  4  5  6  7  8  9 10 11]

reshape(3, 4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

reshape(2, 6):
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

reshape(2, 2, 3):
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]

reshape(4, -1) -> shape: (4, 3)


In [63]:
# # [과제 1] 1부터 100까지의 숫자 중 3의 배수만 포함하는 배열 생성
# # 힌트: np.arange와 step 활용
# arr3 = np.arange(3, 101, 3)
# arr3_1 = (np.arange(1, 101, 3) -1)[1:]
# print(arr3)
# print(arr3_1)


# [과제 2] 5x5 체크보드 패턴 생성 (0과 1이 번갈아 나타남)
# 힌트: zeros로 시작, 슬라이싱으로 값 채우기
checkerboard = np.zeros( (5, 5) )
print(checkerboard)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [74]:
checkerboard[ : : 2, (1,3)] = 1
checkerboard[1: : 2, 0::2] = 1
print(checkerboard)

[[0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]]


In [68]:
checkerboard[1,1]

np.float64(0.0)

In [102]:
np.random.rand(3, 2)

array([[0.10147154, 0.66350177],
       [0.00506158, 0.16080805],
       [0.54873379, 0.6918952 ]])

In [77]:
np.random.randn(2, 4)

array([[-1.95967012, -1.32818605,  0.19686124,  0.73846658],
       [ 0.17136828, -0.11564828, -0.3011037 , -1.47852199]])

In [103]:
x = np.random.rand(100000)*10
print(x)
x.mean()

[6.5196126  2.24269309 7.12179221 ... 4.83238748 8.15225235 2.67119152]


np.float64(4.995448572632296)

In [106]:
np.random.seed(72)
x = (np.random.rand(100) * 10).astype(np.int32)
x.sort()
x[50], x.mean()

(np.int32(4), np.float64(4.09))

In [109]:
temp = np.array( [np.random.randint(100) for i in range(100)] )
print(temp)
temp.sort()
temp[50], temp.mean()

[70 33 91 94 44 76 19 65 37 89 31 42 23 28 27 32 87 84 55 84 32 59 34 65
 91 99 17 85 33 93 37 37 63 17 86 40 60 90 64 53 70 60 84 53 54 64 79 10
 40 71 48 96 63 78 76 32 64 28 21 12 97 51  3 22 32 64 35 42 79 43 52 20
  1 28 18 55 32 61 17 40 84  7 67 30 53 65 66 71  2 24 34 31 96 32 49 20
 93 67 75 90]


(np.int64(53), np.float64(52.17))

In [114]:
samples = np.random.normal(loc = 50, scale = 10, size = 1000)
samples.mean(), samples.std(), samples.max(), samples.min()

(np.float64(50.365844345807616),
 np.float64(10.19853455255535),
 np.float64(80.24141566013371),
 np.float64(19.123165522523916))

In [115]:
samples = np.random.randn(1000,)
samples.mean(), samples.std()

(np.float64(-0.08003027421409657), np.float64(0.9927497375903677))

1. 균등 분할 : 통계 - 어느 값을 뽑더라도 같은 값, 평균과 중위수가 같다 (초기값을 설정)
2. 균등 분포 : 값의 차이가 같은 분포
3. 정규 분포 : 중심을 기준으로 좌우로 퍼져있는 형태 - 실제 데이터와 유사한 형태(머신러닝 또는 딥러닝)